### ISSUE TITLE
psc-package doesn't work on Win 8.1

### ISSUE THREAD

**Issue by Boscop** [purescript/psc-package#78]
I installed everything with `npm install -g purescript pulp psc-package` but psc-package isn't working, why?
```
> psc-package --help
events.js:160
      throw er; // Unhandled 'error' event
      ^
 
Error: spawn C:\Users\me\AppData\Roaming\npm\node_modules\psc-package\vendor\psc-package.exe ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

**Comment by hdgarrood** [comment]
I'm not sure (I'd hazard a guess that the installation didn't work and reinstalling might fix it?). Anyway, this is really an issue with https://github.com/joneshf/node-psc-package-bin (the npm package is sort of separate from what goes on in this repository); would you mind asking there instead?
